Repository JoselFO8/sportShop-api, pull requests merged in 2022-07, with the labels that each got.

#1 Adaptar pi
  .env
  .github/workflows/pipeline.yml
  .gitignore
  index.js
  package.json
  src/db.js
  src/handleDB.js
  src/models/Category.js
  src/models/Pokemon.js
  src/models/Product.js
  src/routes/index.js
  src/routes/products.js
  tests/models/pokemon.spec.js
  tests/routes/endpoints.test.js
  tests/routes/pokemon.spec.js
Labels: good first issue

#10 End points/user
  index.js
  src/db.js
  src/models/Carry.js
  src/models/User.js
  src/routes/carry/functions.js
  src/routes/carry/index.js
  src/routes/index.js
  src/routes/users/functions.js
  src/routes/users/index.js
Labels: enhancement

#13 Feature readme create
  text.txt
Labels: documentation

#14 agregue texto en linea 5
  text.txt
Labels: enhancement

#16 fix-products
  .env
  src/routes/products/function.js
  src/routes/products/index.js
  src/routes/users/index.js
Labels: enhancement

#25 Cris branch
  .env
  src/routes/products/function.js
Labels: documentation, enhancement
